### ISSUE TITLE
Escape sequences in JSON output

### ISSUE THREAD

**Issue by layton-dev** [aide/aide#136]
Hello,

After trying to parse AIDE's output (in JSON format) with the JSON Python module, I've encountered the following error :

```
Traceback (most recent call last):

  File "...", line 111, in <module>
    run_aide()

  File "...", line 53, in run_aide
    parser.parse()

  File "...", line 22, in parse
    json_data=json.load(json_file)

  File "/usr/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),

  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)

  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "/usr/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)

json.decoder.JSONDecodeError: Invalid \escape: line ... column ... (char ...)
```
It was caused by the following line in the JSON file :

```
"/run/user/1000/systemd/generator.late/app-caribou\x2dautostart-autostart.service": "f++++++++++++",
```

It seems that the "\\" in the filename was interpreted as an escape sequence, maybe a simple fix would be to escape all backslashes in file PATHs ?

**Comment by wdoekes** [comment]
Looks like the `different_attributes` entry wasn't fixed:

https://github.com/aide/aide/commit/80c5292dbd3936f757c0de3be2422be6dd00a31b#diff-8ce1593f5495723594c547652c1f8cdc68c608fae252141f4fb23ad0bdc164c7R299-R313
